# Generated by Django 2.0.5 on 2018-06-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonereviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='phonereviewsapp.Phone'),
        ),
    ]
