# Generated by Django 2.0.5 on 2018-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonereviewsapp', '0003_auto_20180608_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phonereviewsapp'),
        ),
        migrations.AddField(
            model_name='store',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='stateOrProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='zipCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
