# Generated by Django 2.0.5 on 2018-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonereviewsapp', '0004_auto_20180608_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonereview',
            name='comment',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
