# Generated by Django 2.0.5 on 2018-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonereviewsapp', '0007_auto_20180610_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='proccessor',
            new_name='processor',
        ),
    ]
