# Generated by Django 2.0.5 on 2018-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonereviewsapp', '0008_auto_20180610_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
